// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // SEKARANG SUDAH ADA CONFIG WEB, JADI TIDAK AKAN ERROR LAGI
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- CONFIG WEB (YANG KITA TAMBAHKAN MANUAL) ---
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBSHvmJCuC63cH4a7kLUSP2EOwnVk53-_w",
    authDomain: "field-operation-mobile.firebaseapp.com",
    databaseURL: "https://field-operation-mobile-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "field-operation-mobile",
    storageBucket: "field-operation-mobile.firebasestorage.app",
    messagingSenderId: "286545418200",
    appId: "1:286545418200:web:1a7c73a4cf4fac45a3c4ad",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu3X-S2ganN6YZJv4E_0GZUDUjkQKHYV4',
    appId: '1:286545418200:android:a01840e9de008316a3c4ad',
    messagingSenderId: '286545418200',
    projectId: 'field-operation-mobile',
    databaseURL: 'https://field-operation-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'field-operation-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeWaImmkw7BOObxL7ZZjWXZk092VgtMFs',
    appId: '1:286545418200:ios:d2bd15081f0aea06a3c4ad',
    messagingSenderId: '286545418200',
    projectId: 'field-operation-mobile',
    databaseURL: 'https://field-operation-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'field-operation-mobile.firebasestorage.app',
    iosBundleId: 'com.example.fieldOperationMobile',
  );
}